// Styles:
import "@/styles/globals.css";
import { cn } from "@/utils";

// Providers:
import { cookies } from "next/headers";
import { TRPCReactProvider } from "@/server/trpc/react";
import { ThemeProvider } from "@/components/theme-provider";

// Fonts:
import localFont from "next/font/local";
import Header from "@/components/header";

const interVariable = localFont({
  variable: "--font-sans",
  src: "../fonts/InterVariable.woff2",
  weight: "100 900",
  display: "swap",
  preload: true,
});

const calsansSemibold = localFont({
  variable: "--font-headings",
  src: "../fonts/CalSans-SemiBold.woff2",
  weight: "600",
  display: "swap",
  preload: true,
});

// Metadata:
export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

// Layout:
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={cn(
          `font-sans ${interVariable.variable} ${calsansSemibold.variable} antialiased`,
          "dark:bg-neutral-900 bg-white",
        )}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Header />
          <TRPCReactProvider cookies={cookies().toString()}>
            {children}
          </TRPCReactProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
